name: Deploy AWS 

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  actions: read
  id-token: write
  attestations: write
  contents: read
  packages: read 
  security-events: write
jobs:
  deploy-aws:
    uses: Fundacion-Dinero-Conciencia/github-template/.github/workflows/deploy-aws.yml@v11
    with:
      environment: pro
    secrets: inherit
